### PR TITLE
- Updated File test to work with updated File component

### LINKED ISSUE #6: Test for File component is broken
The test for the File component is broken. It looks like when #5 was merged in the tests were still looking for the prior structure of props / markup.

### PR DESCRIPTION
**Pull request by derickwarshaw**
- Added key to list being iterated based on index
- Broke out into separate tests to check for the component rendering and looking for the value of a specific element's text based on the props that hydrate
- Added a test that checks for absence of array of componentProps

This resolves #6

### CODE REVIEW

File: src/client/components/File.js [hunk 1]
```diff
@@ -2,9 +2,9 @@ const React = require('react');
 
 const File = (props) => {
   const { componentProps, filename, name = {} } = props;
-  const propTypeDisplay = componentProps ? componentProps.map((property) => {
+  const propTypeDisplay = componentProps ? componentProps.map((property, index) => {
     return (
-      <li>{property.name} - {property.type}</li>
+      <li key={`prop${index}`}>{property.name} - {property.type}</li>
```
Comment (derickwarshaw) [inline src/client/components/File.js:7]: Jest complained about the li not having an unique key.

**Comment by bbohen** [comment]
@derickwarshaw Thanks! I need to get back to work on this thing 😬
